object Form2: TForm2
  Left = 0
  Top = 0
  Margins.Left = 5
  Margins.Top = 5
  Margins.Right = 5
  Margins.Bottom = 5
  BorderIcons = [biSystemMenu]
  BorderStyle = bsSingle
  Caption = 'AI API Keys manager'
  ClientHeight = 533
  ClientWidth = 1169
  Color = clBtnFace
  Font.Charset = DEFAULT_CHARSET
  Font.Color = clWindowText
  Font.Height = -17
  Font.Name = 'Tahoma'
  Font.Style = []
  OnCreate = FormCreate
  PixelsPerInch = 144
  TextHeight = 21
  object Label1: TLabel
    Left = 24
    Top = 29
    Width = 50
    Height = 21
    Margins.Left = 5
    Margins.Top = 5
    Margins.Right = 5
    Margins.Bottom = 5
    Caption = 'Claude'
  end
  object Label2: TLabel
    Left = 24
    Top = 89
    Width = 74
    Height = 21
    Margins.Left = 5
    Margins.Top = 5
    Margins.Right = 5
    Margins.Bottom = 5
    Caption = 'DeepSeek'
  end
  object Label3: TLabel
    Left = 24
    Top = 149
    Width = 51
    Height = 21
    Margins.Left = 5
    Margins.Top = 5
    Margins.Right = 5
    Margins.Bottom = 5
    Caption = 'Gemini'
  end
  object Label4: TLabel
    Left = 24
    Top = 209
    Width = 34
    Height = 21
    Margins.Left = 5
    Margins.Top = 5
    Margins.Right = 5
    Margins.Bottom = 5
    Caption = 'Grok'
  end
  object Label5: TLabel
    Left = 24
    Top = 269
    Width = 50
    Height = 21
    Margins.Left = 5
    Margins.Top = 5
    Margins.Right = 5
    Margins.Bottom = 5
    Caption = 'Mistral'
  end
  object Label6: TLabel
    Left = 24
    Top = 329
    Width = 56
    Height = 21
    Margins.Left = 5
    Margins.Top = 5
    Margins.Right = 5
    Margins.Bottom = 5
    Caption = 'OpenAI'
  end
  object Label7: TLabel
    Left = 24
    Top = 389
    Width = 72
    Height = 21
    Margins.Left = 5
    Margins.Top = 5
    Margins.Right = 5
    Margins.Bottom = 5
    Caption = 'Perplexity'
  end
  object Edit1: TEdit
    Left = 180
    Top = 24
    Width = 938
    Height = 29
    Margins.Left = 5
    Margins.Top = 5
    Margins.Right = 5
    Margins.Bottom = 5
    PasswordChar = '*'
    TabOrder = 0
  end
  object Edit2: TEdit
    Left = 180
    Top = 84
    Width = 938
    Height = 29
    Margins.Left = 5
    Margins.Top = 5
    Margins.Right = 5
    Margins.Bottom = 5
    PasswordChar = '*'
    TabOrder = 1
  end
  object Edit3: TEdit
    Left = 180
    Top = 144
    Width = 938
    Height = 29
    Margins.Left = 5
    Margins.Top = 5
    Margins.Right = 5
    Margins.Bottom = 5
    PasswordChar = '*'
    TabOrder = 2
  end
  object Edit4: TEdit
    Left = 180
    Top = 204
    Width = 938
    Height = 29
    Margins.Left = 5
    Margins.Top = 5
    Margins.Right = 5
    Margins.Bottom = 5
    PasswordChar = '*'
    TabOrder = 3
  end
  object Edit5: TEdit
    Left = 180
    Top = 264
    Width = 938
    Height = 29
    Margins.Left = 5
    Margins.Top = 5
    Margins.Right = 5
    Margins.Bottom = 5
    PasswordChar = '*'
    TabOrder = 4
  end
  object Edit6: TEdit
    Left = 180
    Top = 324
    Width = 938
    Height = 29
    Margins.Left = 5
    Margins.Top = 5
    Margins.Right = 5
    Margins.Bottom = 5
    PasswordChar = '*'
    TabOrder = 5
  end
  object Edit7: TEdit
    Left = 180
    Top = 384
    Width = 938
    Height = 29
    Margins.Left = 5
    Margins.Top = 5
    Margins.Right = 5
    Margins.Bottom = 5
    PasswordChar = '*'
    TabOrder = 8
  end
  object Button1: TButton
    Left = 884
    Top = 458
    Width = 112
    Height = 37
    Margins.Left = 5
    Margins.Top = 5
    Margins.Right = 5
    Margins.Bottom = 5
    Caption = '&Load'
    TabOrder = 6
    OnClick = Button1Click
  end
  object Button2: TButton
    Left = 1005
    Top = 458
    Width = 113
    Height = 37
    Margins.Left = 5
    Margins.Top = 5
    Margins.Right = 5
    Margins.Bottom = 5
    Caption = '&Save'
    TabOrder = 7
    OnClick = Button2Click
  end
  object TMSMCPCloudAI1: TTMSMCPCloudAI
    Service = aiOpenAI
    Settings.GeminiModel = 'gemini-1.5-flash-latest'
    Settings.OpenAIModel = 'gpt-4o'
    Settings.OpenAISoundModel = 'gpt-4o-mini-tts'
    Settings.GrokModel = 'grok-beta'
    Settings.ClaudeModel = 'claude-3-5-sonnet-20241022'
    Settings.OllamaModel = 'llama3.2:latest'
    Settings.DeepSeekModel = 'deepseek-chat'
    Settings.PerplexityModel = 'sonar-pro'
    Settings.OllamaHost = 'localhost'
    Settings.OllamaPath = '/api/chat'
    Settings.MistralModel = 'mistral-large-latest'
    Tools = <>
    Left = 488
    Top = 288
  end
end
